### ISSUE TITLE
estnltk build fails on colab.research

### ISSUE THREAD

**Issue by kunnark** [estnltk/estnltk#107]
Having trouble installing estnltk tools to colab.research. Building from git or natively from pip fails. Can you advise?

`!pip install git+https://github.com/estnltk/estnltk.git`

`Collecting git+https://github.com/estnltk/estnltk.git
  Cloning https://github.com/estnltk/estnltk.git to /tmp/pip-req-build-l2mzrjrq
  Running command git clone -q https://github.com/estnltk/estnltk.git /tmp/pip-req-build-l2mzrjrq
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (1.12.0)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (3.2.5)
Requirement already satisfied: regex>=2015.07.19 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (2019.6.8)
Requirement already satisfied: pandas>=0.18 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (0.24.2)
Requirement already satisfied: python-crfsuite>=0.8.4 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (0.9.6)
Requirement already satisfied: cached-property>=1.2.0 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (1.5.1)
Requirement already satisfied: beautifulsoup4>=4.4.0 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (4.6.3)
Requirement already satisfied: html5lib>=0.9999999 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (1.0.1)
Requirement already satisfied: elasticsearch==2 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (2.0.0)
Requirement already satisfied: pyahocorasick>=1.1.4 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (1.4.0)
Requirement already satisfied: unicodecsv>=0.14.1 in /usr/local/lib/python3.6/dist-packages (from estnltk==1.4.1.1) (0.14.1)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18->estnltk==1.4.1.1) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18->estnltk==1.4.1.1) (2.5.3)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.18->estnltk==1.4.1.1) (1.16.4)
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/dist-packages (from html5lib>=0.9999999->estnltk==1.4.1.1) (0.5.1)
Requirement already satisfied: urllib3<2.0,>=1.8 in /usr/local/lib/python3.6/dist-packages (from elasticsearch==2->estnltk==1.4.1.1) (1.24.3)
Building wheels for collected packages: estnltk
  Building wheel for estnltk (setup.py) ... error
  ERROR: Failed building wheel for estnltk
  Running setup.py clean for estnltk
Failed to build estnltk
Installing collected packages: estnltk
  Running setup.py install for estnltk ... error
ERROR: Command "/usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-l2mzrjrq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-byw1ie85/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-l2mzrjrq/`

**Comment by swenlaur** [comment]
Everybody is on vacation now so it might take a while now. 
Links for debugging the issues follow. No solution yet. 

The environment for he google colab platform seems to be (was) Ubuntu version: "17.10 (Artful Aardvark)"
https://github.com/NanoComp/meep/issues/460

It can be queried as follows
https://stackoverflow.com/questions/47805170/whats-the-hardware-spec-for-google-colaboratory 

If possible we try to replicate the install and see do we get the same error and how to fix it
https://stackoverflow.com/questions/47276071/how-to-install-extra-packages-in-google-colaboratorys-vm

**Comment by soras** [comment]
Hi! 

I tried estnltk's installation on colab.research, and currently, there is a lot of hassle with it. 

First of all, in order to install and build estnltk via `pip`, you need to have [Swig](http://www.swig.org/) installed. This can be done nicely with the command:
`!apt-get install g++ libpcre3 libpcre3-dev swig`
After that, I was able to successfully install estnltk v1.4 via `pip`, but once I tried to use it, the command `from estnltk import Text` gave me an error (`ImportError: cannot import name 'vabamorf'`). So, it seems that something went wrong with creating the _vabamorf_ module. I also tried building and installing estnltk v1.4 without `pip` (`python setup.py build_ext install`), and again, 
 installing was successful, but the usage gave an import error.
I suspect that problems are related to the fact that colab.research uses Python 3.6, but the highest Python version that estnltk v1.4 can handle is 3.5.

I also tried out installation using [conda](https://docs.conda.io/en/latest/).  There is a hassle with it too, but at the end of the day, I got it somehow working. Here are the steps:
1. First, you need to install conda, preferably [miniconda](https://repo.continuum.io/miniconda/):
`!wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh`
`!chmod +x Miniconda3-latest-Linux-x86_64.sh`
`!bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p miniconda`
In my environment, it installed `miniconda` at the location `/content/miniconda`.
2. Create a new environment that has Python 3.5:
`!/content/miniconda/bin/conda create -n py35 python=3.5`
Now, I was not able to activate the environment. But I managed to bypass the activation, and still install estnltk v1.4.
3. Install estnltk v1.4:
`!/content/miniconda/bin/conda install --prefix /content/miniconda/envs/py35 -c estnltk -c conda-forge estnltk=1.4.1`
4. After the installation is successful, you should be able to execute small snippets of Python 3.5 code or scripts in a following way:
`!/content/miniconda/envs/py35/bin/python -c "import estnltk; print( estnltk.Text('Tere estnltk').lemmas )"`
output:
`[nltk_data] Downloading package punkt to /root/nltk_data...`
`[nltk_data]   Unzipping tokenizers/punkt.zip.`
`['tere', 'estnltk']`

But this _conda_ solution is not very nice. Hopefully, someone finds a better soultion in the future.

**Comment by soras** [comment]
A progress on the issue. 
I merged Vabamorf's source fixes from [the issue 97](https://github.com/estnltk/estnltk/issues/97) and [pull 109](https://github.com/estnltk/estnltk/pull/109), and I built a [manylinux](https://github.com/pypa/manylinux) pip wheel with estnltk 1.6.5beta. As far as I have tested, this wheel now installs and runs on colab.research.

The wheel is available on [https://test.pypi.org/project/estnltk/#files](https://test.pypi.org/project/estnltk/#files), and should be installable to colab.research with the following command:
```
!pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple  estnltk==1.6.5.4beta
```
Note that the wheel's current location is temporary, and it is a bit unofficial release. Once we have fully merged and tested the fixes, there will be a wheel at a more permanent location.

**Comment by soras** [comment]
Instructions for building EstNLTK packages that can be used in Google Colab are available [here](https://github.com/estnltk/estnltk/tree/6d574f2ed097e67f3122c9502a06dfde1a2b3b4a/dev_documentation/PyPi_package_for_Google_Colab).

You can now install the latest version of estnltk in colab with the command:
```
!pip install conllu estnltk==1.6.6b0
```
Closing this issue.
